<a href="https://colab.research.google.com/github/TanSha15/FeatureExtractionProject/blob/main/Feature_Extraction_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as pd
import pandas as pd

In [ ]:
data = pd.read_csv(r'anime.csv')

In [ ]:
df = pd.DataFrame(data)

In [ ]:
#feature extraction
#no seperate col. but we will extract the episode count from title
def extract_episode(txt):
  data = ""
  check = False
  for i in txt:
    if i == '(':
      check = True
      continue
    if i == ')':
      break
    if check == True:
      data += i
  return data if data else None

In [ ]:
#apply the function on Title
df['Episodes'] = df['Title'].apply(extract_episode)

In [ ]:
#Now remove the _eps from the epsidoes last
df['Episodes'] = df['Episodes'].str.replace(' eps', '')

In [ ]:
#Now convert in into the integer
df['Episodes'] = df['Episodes'].astype(int)

In [ ]:
#Now extracting timestamp from title again defining func
def extract_timestamp(txt):
  count = 0
  for i in txt:
    count+=1
    if i == ')':
      break
  data = ""
  for i in range(count,count+19):
    data+=txt[i]
  return data

In [ ]:
#apply the feature and create a new col Time_Stamp
df['TimeStamp'] = df['Title'].apply(extract_timestamp)

In [ ]:
#Now calculate total months used chatgpt to define the functions
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1  # +1 to include the starting month
    except:
        return None

In [ ]:
#applying the function
df['Months'] = df['TimeStamp'].apply(calculate_total_months)

In [ ]:
df[df['Score'] == df['Score'].max()]

,Rank,Title,Score,Episodes,TimeStamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,16

In [ ]:
df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,TimeStamp,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [ ]:
#final table
df.head()

,Rank,Title,Score,Episodes,TimeStamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4